[package]
name = "morphological_tokenization"
version = "0.1.0"
edition = "2021"

[dependencies]
clustering = { version = "0.2.1", features = ["parallel"] }
ml_experiments = {path = "../..", version = "*"}
once_cell = "1.19.0"
rand = "0.8.5"
